In [ ]:
####This code does the one hot encoding for five existing features.
import pandas as pd
df = pd.read_csv("E:\\jup\\xtest.csv")

dummies = pd.get_dummies(df.Month)
merged1 = pd.concat([df,dummies],axis='columns')
final1 = merged1.drop(['Month'],axis='columns')


dummies_province = pd.get_dummies(final1.Province)
#dummies_province_dropped = dummies_province.drop([9],axis='columns')
merged2 = pd.concat([final1,dummies_province_dropped],axis='columns')
final2 = merged2.drop(['Province'],axis='columns')


dummies_browser = pd.get_dummies(final2.Browser)
#dummies_browser_dropped = dummies_browser.drop([1],axis='columns')
merged3 = pd.concat([final2,dummies_browser_dropped],axis='columns')
final3 = merged3.drop(['Browser'],axis='columns')


dummies_operatingSystems = pd.get_dummies(final3.OperatingSystems)
#dummies_operatingSystems_dropped = dummies_operatingSystems.drop([1],axis='columns')
merged4 = pd.concat([final3,dummies_operatingSystems_dropped],axis='columns')
final4 = merged4.drop(['OperatingSystems'],axis='columns')

dummies_VisitorType = pd.get_dummies(final4.VisitorType)
#dummies_VisitorType_dropped = dummies_VisitorType.drop(['Other'],axis='columns')
merged5 = pd.concat([final4,dummies_VisitorType_dropped],axis='columns')
final5 = merged5.drop(['VisitorType'],axis='columns')

print(final5.shape)


f=pd.DataFrame(final5)
f.to_csv('E:\jup\sample_xtest.csv',index=False,)

In [91]:
####This code does the one hot encoding for five existing features.
import pandas as pd
df = pd.read_csv("E:\\jup\\Trainset.csv")

dummies = pd.get_dummies(df.Month)
merged1 = pd.concat([df,dummies],axis='columns')
final1 = merged1.drop(['Month'],axis='columns')


dummies_province = pd.get_dummies(final1.Province)

merged2 = pd.concat([final1,dummies_province],axis='columns')
final2 = merged2.drop(['Province'],axis='columns')


dummies_browser = pd.get_dummies(final2.Browser)

merged3 = pd.concat([final2,dummies_browser],axis='columns')
final3 = merged3.drop(['Browser'],axis='columns')


dummies_operatingSystems = pd.get_dummies(final3.OperatingSystems)

merged4 = pd.concat([final3,dummies_operatingSystems],axis='columns')
final4 = merged4.drop(['OperatingSystems'],axis='columns')

dummies_VisitorType = pd.get_dummies(final4.VisitorType)

merged5 = pd.concat([final4,dummies_VisitorType],axis='columns')
final5 = merged5.drop(['VisitorType'],axis='columns')

print(final5.shape)

f=pd.DataFrame(final5)
f.to_csv('E:\jup\sample_Trainset.csv',index=False,)

In [3]:
import pandas as pd
df = pd.read_csv("E:\\jup\\xtest.csv")
print(df.shape)

(1850, 59)


In [83]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import math as ma

import os
for dirname, _, filenames in os.walk('/kaggle/input/'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [6]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import math as ma

import os
#for dirname, _, filenames in os.walk('/kaggle/input/'):
 #   for filename in filenames:
 #       print(os.path.join(dirname, filename))

#Trainset = pd.read_csv("/kaggle/input/hackstat2k19/Trainset.csv", header = 0) 
Trainset = pd.read_csv("E:\\jup\\Trainset.csv", header = 0)
Trainset = Trainset.dropna()

sampleset = pd.read_csv("E:\\jup\\sample_submisison.csv", header = 0) 
sampleset = sampleset.dropna()

#Trainset  = Trainset.replace(to_replace=['Jan', 'Feb','Mar','Apr','May','June','Jul','Aug','Sep','Oct','Nov','Dec'], value=[0,2,166,0,307,21,54,69,72,97,641,183])
#Trainset  = Trainset.replace(to_replace=['Returning_Visitor', 'New_Visitor' , 'Other'], value=[1242, 366, 11])

xset = pd.read_csv("E:\\jup\\xtest.csv")
xset = xset.dropna()

#xset  = xset.replace(to_replace=['Jan', 'Feb','Mar','Apr','May','June','Jul','Aug','Sep','Oct','Nov','Dec'], value=[0,2,166,0,307,21,54,69,72,97,641,183])
#xset  = xset.replace(to_replace=['Returning_Visitor', 'New_Visitor' , 'Other'], value=[1242, 366, 11])

#Trainset['is_train'] = np.random.uniform(0,1,len(Trainset)) <= 0.75
print(Trainset)

Train, Test = Trainset,xset

print('Number of Training examples', len(Train))
print('Number of Testing examples', len(Test))

features = Trainset.columns[:52]
print(features)
y = Train['Revenue']
y

id_ = sampleset['ID']
#new_ = id_.DataFarame(id_)
clf = RandomForestClassifier(n_jobs = 2, random_state = 0)
clf.fit(Train[features],y)

clf.predict(Test[features])

#clf.predict_proba(Test[features])

preds = clf.predict(Test[features])

#print(tpe(new_))
#print(type(preds))
YArray= id_.as_matrix(columns=None)
print (YArray)

df = pd.DataFrame({"ID" : YArray, "Revenue" : preds})
df.to_csv("E:\\jup\\submission.csv", index=False)
#dfObj = pd.DataFrame(YArray,preds,columns = ["ID","Revenue"]) 

#dfObj.to_csv('submit.csv', index = False)

#pd.crosstab(Test['Revenue'], preds, rownames = ['Actual Revenue'], colnames = ['Predicted Revenue'])
#Test['Revenue']
#X, y = Trainset.iloc[:, :16], Trainset.iloc[:, 17]

#Xset = xset.iloc[:, :16]
#print(X)
#print(y)

#clf = RandomForestClassifier(n_estimators=10)
#clf = clf.fit(X, y)
#clf

#clf = RandomForestClassifier(n_estimators=17, max_depth=None,min_samples_split=2, random_state=0)
#scores = cross_val_score(clf, X, y, cv=5)
#scores.mean() 

        Division1   Division2   Division3  BounceRates  ExitRates  PageValues  \
0       10.000000    0.000000   77.777778     0.000000   0.011111   29.621890   
1        7.500000    0.000000   89.466667     0.000000   0.022222    0.000000   
2       85.000000    0.000000   21.892857     0.000000   0.004444    0.000000   
3       35.020000    0.000000   23.675366     0.000000   0.002083   62.773672   
4       12.500000    0.000000    8.000000     0.066667   0.083333    0.000000   
5      113.750000    0.000000   73.272253     0.022667   0.034600   11.706146   
6        0.000000    0.000000   30.647565     0.009804   0.017358    0.000000   
7       11.429630  113.166667   23.905316     0.000000   0.014706   77.649145   
8       12.325000    0.000000   43.747436     0.000000   0.012500    0.000000   
9        8.000000    0.000000   31.054823     0.010417   0.017639    0.000000   
10       0.000000    0.000000   42.874359     0.015385   0.026099   26.130349   
11      35.083333    0.00000

C:\Users\User\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


[   1    2    3 ... 1848 1849 1850]


C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:55: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.


In [5]:
import pandas as pd
df = pd.read_csv("E:\\jup\\xtest.csv")

fi=pd.DataFrame(df)
fi.to_csv('E:\\jup\\xtestV1.csv',index=False,)

In [2]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import math as ma
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

import os
#for dirname, _, filenames in os.walk('/kaggle/input/'):
 #   for filename in filenames:
  #      print(os.path.join(dirname, filename))

Trainset1 = pd.read_csv("E:\\sample\\Trainset.csv", header = 0) 
Trainset1 = Trainset1.dropna()

sampleset = pd.read_csv("E:\\sample\\sample_submisison.csv", header = 0) 
sampleset = sampleset.dropna()

dummies1 = pd.get_dummies(Trainset1.Month)
dummies1 = dummies1.drop(['Feb'], axis = 'columns')
merged1 = pd.concat([Trainset1,dummies1],axis = 'columns')

dummies2 = pd.get_dummies(merged1.VisitorType)
dummies2 = dummies2.drop(['Other'], axis = 'columns')
merged2 = pd.concat([merged1,dummies2],axis = 'columns')

dummies3 = pd.get_dummies(merged2.OperatingSystems)
dummies3 = dummies3.drop([1], axis = 'columns')
merged3 = pd.concat([merged2,dummies3],axis = 'columns')

dummies4 = pd.get_dummies(merged3.Browser)
dummies4 = dummies4.drop([1], axis = 'columns')
merged4 = pd.concat([merged3,dummies4],axis = 'columns')

dummies5 = pd.get_dummies(merged4.Province)
dummies5 = dummies5.drop([1], axis = 'columns')
merged5 = pd.concat([merged4,dummies5],axis = 'columns')

y = merged5['Revenue']
##y = y.iloc[0:300]
Trainset = merged5.drop(['Month','VisitorType','Weekend','OperatingSystems','Browser','Province','Revenue'], axis = 'columns')
X=Trainset
xset1 = pd.read_csv("E:\\sample\\xtest.csv")
xset1 = xset1.dropna()

xdummies1 = pd.get_dummies(xset1.Month)
# xdummies1 = xdummies1.drop(['Feb'], axis = 'columns')
xmerged1 = pd.concat([xset1,xdummies1],axis = 'columns')

xdummies2 = pd.get_dummies(xmerged1.VisitorType)
# xdummies2 = xdummies2.drop(['Other'], axis = 'columns')
xmerged2 = pd.concat([xmerged1,xdummies2],axis = 'columns')

xdummies3 = pd.get_dummies(xmerged2.OperatingSystems)
# xdummies3 = xdummies3.drop([1], axis = 'columns')
xmerged3 = pd.concat([xmerged2,xdummies3],axis = 'columns')

xdummies4 = pd.get_dummies(xmerged3.Browser)
#xdummies4 = xdummies4.drop([1], axis = 'columns')
xmerged4 = pd.concat([xmerged3,xdummies4],axis = 'columns')

xdummies5 = pd.get_dummies(xmerged4.Province)
#xdummies5 = xdummies5.drop([1], axis = 'columns')
xmerged5 = pd.concat([xmerged4,xdummies5],axis = 'columns')
# X = xmerged5.drop(['Month','VisitorType','Weekend','OperatingSystems','Browser','Province'], axis = 'columns').iloc[0:300]

# Train = Trainset,xset
# Test = xset
# print('Number of Training examples', len(Train))
# print('Number of Testing examples', len(Test))

# features = Train.columns[:37]
# print(features)
#y = Train['Revenue']


# id_ = sampleset['ID']
# #new_ = id_.DataFarame(id_)
# clf = RandomForestClassifier(n_jobs = 2, random_state = 0)
# clf.fit(Train[features],y)

# clf.predict(Test[features])

# print(Test[features])

# preds = clf.predict(Test[features])

# YArray= id_.as_matrix(columns=None)
# print (YArray)

# df = pd.DataFrame({"ID" : YArray, "Revenue" : preds})
# df.to_csv("submission.csv", index=False)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)
# svclassifier = SVC(kernel='rbf')
# svclassifier.fit(X_train, y_train)
print(X)
print(y)
y_pred = svclassifier.predict(X_test)
print(y_pred)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))





       Homepage  Homepage _Duration  Aboutus  Aboutus_Duration  Contactus  \
0           1.0           10.000000      0.0              0.00        9.0   
1           2.0           15.000000      0.0              0.00       10.0   
2           1.0           85.000000      0.0              0.00       14.0   
3           5.0          175.100000      0.0              0.00       26.0   
4           2.0           25.000000      0.0              0.00        5.0   
5           1.0          113.750000      0.0              0.00       26.0   
6           0.0            0.000000      0.0              0.00       53.0   
7           9.0          102.866667      3.0            339.50       29.0   
8           4.0           49.300000      0.0              0.00       12.0   
9           1.0            8.000000      0.0              0.00       47.0   
10          0.0            0.000000      0.0              0.00       26.0   
11          6.0          210.500000      0.0              0.00       26.0   

[0 1 0 ... 0 0 1]
[[1724   46]
 [ 191  133]]
              precision    recall  f1-score   support

           0       0.90      0.97      0.94      1770
           1       0.74      0.41      0.53       324

    accuracy                           0.89      2094
   macro avg       0.82      0.69      0.73      2094
weighted avg       0.88      0.89      0.87      2094

